// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9kzSImcEo00gor8PcbFH1vXV6wNu3Q6c',
    appId: '1:476892879888:web:e270d80ce5fd9d03c5fe95',
    messagingSenderId: '476892879888',
    projectId: 'biomakerapp',
    authDomain: 'biomakerapp.firebaseapp.com',
    storageBucket: 'biomakerapp.firebasestorage.app',
    measurementId: 'G-5Y95J6XCLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATXgqBY_x9eiIMq2CrXXmwYc6A1SoRvJk',
    appId: '1:476892879888:android:bad7bda540c89babc5fe95',
    messagingSenderId: '476892879888',
    projectId: 'biomakerapp',
    storageBucket: 'biomakerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQU_17oYgVXEhUIz3TCSASUbkKnfxTTQ',
    appId: '1:476892879888:ios:e39fdda3fe30f90bc5fe95',
    messagingSenderId: '476892879888',
    projectId: 'biomakerapp',
    storageBucket: 'biomakerapp.firebasestorage.app',
    iosBundleId: 'com.example.bioMakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNQU_17oYgVXEhUIz3TCSASUbkKnfxTTQ',
    appId: '1:476892879888:ios:e39fdda3fe30f90bc5fe95',
    messagingSenderId: '476892879888',
    projectId: 'biomakerapp',
    storageBucket: 'biomakerapp.firebasestorage.app',
    iosBundleId: 'com.example.bioMakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9kzSImcEo00gor8PcbFH1vXV6wNu3Q6c',
    appId: '1:476892879888:web:4641458d5710fe35c5fe95',
    messagingSenderId: '476892879888',
    projectId: 'biomakerapp',
    authDomain: 'biomakerapp.firebaseapp.com',
    storageBucket: 'biomakerapp.firebasestorage.app',
    measurementId: 'G-9NRMMY03HG',
  );
}
